### PR TITLE
Correct release year for 2.1.2

### PR DESCRIPTION
**Pull request by demobox**

### CODE REVIEW

**Comment by demobox** [comment]
> gaul merged commit 8ee7b98 into master 1 hour ago

Thanks, gaul!

**Comment by nacx** [comment]
Could you try publishing the site? Make sure you are up to date, then run `make publish`. It now uses Docker to avoid having to install the ancient Jekyll and random ruby stuff, but I'd like to see that it does not only work for me :)

**Comment by gaul** [comment]
@nacx Are there more instruction for this?  I get these results:

```
$ sudo docker build .
...
Successfully built f8cc20a7149a
$ sudo docker run f8cc20a7149a
Switch to inspect mode.
```

**Comment by nacx** [comment]
Why not using the Makefile and the commands I copied above?

If you want to run docker commands manually you can read the contents of the Makefile

**Comment by gaul** [comment]
Sorry I missed the Makefile.  To run the makefile I needed to add:

```Makefile
PWD := $(shell pwd)
```

However this still fails:

```
$ sudo make build
docker run --rm -v "/home/gaul/work/jclouds-site:/jclouds-site" -p 4000:4000 jclouds/site-builder jekyll serve --safe --port 4000
/usr/local/bundle/gems/liquid-2.5.5/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: none
            Source: /jclouds-site
       Destination: /jclouds-site/_site
      Generating... error: Permission denied @ dir_initialize - .. Use --trace to view backtrace
make: *** [Makefile:9: build] Error 1
```

**Comment by nacx** [comment]
I haven't faced that error before. Could it be possible that there are files in there that were owned by root?

**Pull request merged**
