### PR TITLE
Add release notes for 2.2.1

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by gaul** [comment]
@nacx `deploy-site.sh` still requires an old Jekyll -- could you push this for me?

**Comment by nacx** [comment]
I can't do it now, but I'll try tomorrow if you don't beat me at it.
Can you try deploying using the `Makefile` as explained in the [README](https://github.com/apache/jclouds-site/blob/master/README.md)? I dockerized it some time ago to avoid the old-jekyll issues.

**Comment by gaul** [comment]
Thanks for the pointer!  Unfortunately it seems that my desktop is too new:

```
OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown
```

Looks like I can work around this with a reboot which I can try this weekend if you don't beat me to it.

**Comment by nacx** [comment]
Published!
We'll have to update it with proper links once the announcement emails are out.

**Comment by gaul** [comment]
Updated the short links.  Thanks @nacx you saved me a reboot.  :)

**Pull request merged**
